export const subscriptionsSymbol = Symbol('subscriptions')
export const observerSymbol = Symbol('observer')
export const rawSymbol = Symbol('raw')
export const originSymbol = Symbol('origin')
export const setterSymbol = Symbol('setter')
